on: push
jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          pip install pipx
          pipx install hatch
      - run: hatch --version
