name: Python test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: env
      - run: |
          which pipx
          pipx environment
      - name: install stuff
        run: |
          echo $PATH
          which pipx
          pip install pipx
          which pipx
          pipx install hatch
      - run: |
          which pipx
          pipx environment
      - name: run hatch
        run: |
          which hatch
          hatch --version
